Submodules for user directory types
SpineEventEngine/users pull request #52
Opened 2019-09-26 17:34 UTC by alexander-yevsyukov

2019-10-14 14:21 UTC, alexander-yevsyukov commented
@armiol, this is the PR with the draft for new `Client` and `Session` API.

2020-10-12 19:34 UTC, alexander-yevsyukov commented
@armiol, @dmdashenkov PTAL. Significant part of this PR is deleted or moved into other repositories. So it's not real 208 files.

2020-10-12 20:46 UTC, dmdashenkov requested changes
It seems strange to me that there are 2 entities called `UserAccount`, an aggregate part and a projection. I realize that one is part of a DB-specific model while the other is more general. Still would be nice to be able to tell one from the other without checking the package name. Also, I doubt that we would call it the same name in a real-life conversation.

On a more general note, I wonder if projections are the way to go here. Are we emphasizing that the source of truth is "out there and not here"? If so, will we be able to avoid duplicating logic of building this model across different implementations?

2020-10-12 20:46 UTC, dmdashenkov commented on build.gradle.kts
> +    id("com.google.protobuf").version(io.spine.gradle.internal.Deps.versions.protobufPlugin)
Please suppress the warning. Otherwise, IDEA will replace this FQN with an import and break the build.

2020-10-12 20:46 UTC, dmdashenkov commented on build.gradle.kts
> +    id("com.google.protobuf").version(io.spine.gradle.internal.Deps.versions.protobufPlugin)
Same below and in the `buildscript` section.

2020-10-12 20:46 UTC, dmdashenkov commented on build.gradle.kts
> +        //  https://github.com/epeee/junit-jupiter-extension-testing/blob/57b7ba75ab64ed8c229d2a5b14a954d6ae359189/gradle/errorprone.gradle
I don't think this note is necessary. It should be explained in `deps.kt`.

2020-10-12 20:46 UTC, dmdashenkov commented on build.gradle.kts
> +    /* Uncomment this block if you need to display console output during the Gradle build.*/
Please remove this comment.

2020-10-12 20:46 UTC, dmdashenkov commented on users-client/src/main/java/io/spine/users/event/AccountAware.java
> +public interface AccountAware extends EventMessage {
Its probably `AccountAwareEvent`, since it extends `EventMessage`.

2020-10-12 20:46 UTC, dmdashenkov commented on users-client/src/main/java/io/spine/users/event/GroupAware.java
> +public interface GroupAware extends EventMessage {
Same as above.

2020-10-12 20:46 UTC, dmdashenkov commented on users-db/src/main/java/io/spine/users/server/db/GroupAccountPart.java
> +            @SuppressWarnings({
Please move the suppressions to the method level. I know its a bit of an overkill, but this way we don't lose the fluency of an applier method declaration.

2020-10-12 20:46 UTC, dmdashenkov commented on users-db/src/main/java/io/spine/users/server/db/GroupMembersPart.java
> +               .stream();
Please fix the alignment.

2020-10-12 20:46 UTC, dmdashenkov commented on version.gradle.kts
> +    this["spineBaseVersion"] = "1.6.0"
Please use the latest version of base.

2020-10-13 15:25 UTC, armiol requested changes
@alexander-yevsyukov 39/208 reviewed. I have completed the `users-client` code part. Continuing onto the rest of the modules.

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/events.proto
> +    option (required_field) = "new_email|old_email";
I thought we needed the `new_email` to be required and not equal to `old_email`.

The current definition says that a group may have no email — in case someone has erased it, `new_email` is going to be empty and `old_email` is going to be filled in.

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/events.proto
> +// A user was removed a group.
"removed from a group".

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/events.proto
> +    Role role = 3 [(required) = true];
The description says "if available". So I assume this field isn't required.

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/identifiers.proto
> +    string value = 1;
I assume we want to leave this field without any restrictions on its content, as we don't know which ID structure third parties — that we integrate with — have. Is it so?

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/membership.proto
> +// To which groups this user belongs?
While I understand it's for brevity, I would avoid the questions and go with 
`The groups to which this user belongs`.

The same applies to the `GroupMembership` description down below.

2020-10-13 15:25 UTC, armiol commented on users-client/src/main/proto/spine/users/membership.proto
> +    // This means that if the `direct` field is empty, this field must be empty too.
So, `indirect` memberships include `direct` memberships? If so, I would call this field "all". See below (notice the updated description of the `direct` field as well):

```proto
...
    // Groups to which the user belongs directly.
    //
    // Empty if the user is not a member of any group.
    //
    repeated Membership direct = 2;

    // All groups to which the user belongs.
    //
    // Includes the groups to which the user belongs directly and the groups of groups.
    //
    // Empty if the the groups the user belongs to do not belong to other groups.
    // This means that if the `direct` field is empty, this field must be empty too.
    //
    repeated Membership all = 3;
...
```

2020-10-13 15:51 UTC, armiol requested changes
@alexander-yevsyukov 64/208 done. Both `users-client` and `users-db` reviewed. Hopping onto the next module now.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/java/io/spine/users/server/db/ContextExtensions.java
> +    public static BoundedContextBuilder withDatabase(BoundedContextBuilder builder) {
Please document.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/java/io/spine/users/server/db/GroupMembersPart.java
> +                members().filter(m -> m.getKindCase() == USER)
It seems we may shorten this to 
```java
private Optional<Member> findMember(UserId user) {
        Optional<Member> found =
                members().filter(m -> user.equals(m.getUser()))
                         .findFirst();
        return found;
    }
```
Given the passed `user` is not default (which should be guaranteed by the event constraints in the first place), we are going to be fine.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/java/io/spine/users/server/db/GroupMembersPart.java
> +        Optional<Member> found =
Same as above:
```java
    private Optional<Member> findMember(GroupId group) {
        Optional<Member> found =
                members().filter(m -> group.equals(m.getGroup()))
                         .findFirst();
        return found;
    }
```

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/proto/spine/users/db/commands.proto
> +message ResumeUserAccount {
Just in case, see my suggestion on `resume` -> `restore` above.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/proto/spine/users/db/commands.proto
> +// Deletes a group.
Same as above. I would say `Delete` instead of `Deletes`.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/proto/spine/users/db/rejections.proto
> +// A command requests creation of a group with an ID which already assigned to another group.
Let's say `A command requested...`, as in similar cases.

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/proto/spine/users/db/rejections.proto
> +// An operation is not available because a group the passed ID was previously deleted.
`...a group with the passed ID...`

2020-10-13 15:51 UTC, armiol commented on users-db/src/main/proto/spine/users/db/rejections.proto
> +    // The group removal of whom from the group was requested.
`...of which...`

2020-10-13 15:51 UTC, armiol commented on users-db/src/test/java/io/spine/users/server/db/DbCommandTest.java
> +public abstract class DbCommandTest<I, C extends CommandMessage, E extends EventMessage,
As it is an abstract base type, please document its purpose.

2020-10-13 15:51 UTC, armiol commented on users-db/src/test/java/io/spine/users/server/db/DbExtensionsTest.java
> +public abstract class DbExtensionsTest extends UsersContextTest {
Please document this abstract base class.

2020-10-13 15:51 UTC, armiol commented on users-db/src/test/java/io/spine/users/server/db/UserAccountTest.java
> +
Please kill this empty line.

2020-10-13 15:51 UTC, armiol commented on users-db/src/test/java/io/spine/users/server/db/given/Command.java
> +public class Command {
This class seems `final`.

2020-10-13 15:51 UTC, armiol commented on users-db/src/test/java/io/spine/users/server/db/package-info.java
> +package io.spine.users.server.db;
We seem to already have a `package-info` in this package. It is defined in the `main/java` source root.

2020-10-13 18:06 UTC, armiol requested changes
@alexander-yevsyukov `users-google` also done (88/208 reviewed so far in this PR). Please see my comments.

2020-10-13 18:06 UTC, armiol commented on users-google/src/main/proto/spine/users/google/group.proto
> +// `GroupId` of the Users context.
The context in this model is named `Google Directory`. So, I would add some text explaining that you mean not this context, but another. Let's discuss further once we meet.

2020-10-13 18:06 UTC, armiol commented on users-google/src/test/java/io/spine/users/google/server/given/GoogleGroupTestEnv.java
>  public class GoogleGroupTestEnv {
I understand the tests are disabled, but for the sake of reviewing, all the classes in this `.given` package should be `final`.

2020-10-13 20:29 UTC, alexander-yevsyukov commented on users-client/src/main/java/io/spine/users/event/AccountAware.java
> +public interface AccountAware extends EventMessage {
We're in the `event` package. Anything here is most likely an event. Why don't we DRY?

2020-10-13 20:31 UTC, alexander-yevsyukov commented on users-db/src/main/java/io/spine/users/server/db/GroupAccountPart.java
> +            @SuppressWarnings({
Right!

2020-10-14 12:03 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/events.proto
> +    option (required_field) = "new_email|old_email";
`new_email` != `old_email` is a separate story. I don't think our validation supports it.

2020-10-14 12:05 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/events.proto
> +    option (required_field) = "new_email|old_email";
I think there can be general cases when a group had an email address and then lose it. Suppose it's not a Google Group, but just a buch of people who used to have a mailing list. And then, they decided to go to Slack so the group no longer needs an email. So, they ditch the email address and the event reflects that the association with group email address is no longer relevant.

2020-10-14 12:08 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/events.proto
> +    option (required_field) = "new_email|old_email";
I thought about removing the `email` field from the `Group` at all so that the group thing is formulated in more abstract term. But then I leaned toward practicality. Email address is going to be used. At least when it comes to integrating with Google, which is one of the first implementations we're going to have as long as we need it most.

2020-10-14 12:21 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/membership.proto
> +    // This means that if the `direct` field is empty, this field must be empty too.
I've clarified the description. I want to keep direct and indirect separately. It's easy to combine them, if needed.

Just in case Google announced the [support for indirect group membership](https://gsuiteupdates.googleblog.com/2020/10/new-apis-view-visualize-google-group-membership.html).

2020-10-14 12:23 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/identifiers.proto
> +    string value = 1;
Exactly.

2020-10-14 16:25 UTC, alexander-yevsyukov commented on users-google/src/main/java/io/spine/users/google/server/IdMapping.java
> +public class IdMapping
As discussed vocally, let's keep it this way for now. Integration with Google Workspace API may change significantly really soon.

2020-10-14 16:56 UTC, alexander-yevsyukov commented on users-client/src/main/proto/spine/users/events.proto
> +    Role role = 3 [(required) = true];
Let's have all the `role` field required. It would simplify a bit the code consuming the events.

2020-10-14 20:54 UTC, armiol approved these changes
@alexander-yevsyukov LGTM.

2020-10-15 09:42 UTC, dmdashenkov approved these changes

2020-10-15 11:07 UTC, merged